### ISSUE TITLE
Treure conyes del repositori

### ISSUE THREAD

**Issue by jordi-petit** [llop/cpp-ide#1]
Eo! Més que res estic provant el sistema aquest de les issues :-) A més, he fet un watch del teu projecte, així aniré vient com avança.

Hauries de treure les dependències del repositori:
- [x] Tot el node_modules no pertoca. Quan instal·lis un mòdul fés `npm install mòdul --save` i ja el ficarà al `package.json` i el reinstal·laràs amb `npm install`. 
- [x] Pels paquets del client, igual: El millor és ficar-te dins de `public` i fer alguna cosa com `bower install ace-builds jeasyui term.js`. Però aquests no sé encara com es graven/on es fiquen.

**Comment by llop** [comment]
Hola Jordi! Ja he tret el directori node_modules.
I he afegit el bower per gestionar els .js del client.
Salut! :)
